//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GUIApp.rc
//
#define ID_LOAD                         2
#define IDC_FRAGMENT                    2
#define IDC_NEW_SURFACE                 2
#define IDRESET                         3
#define IDC_TEST_SAMPLE                 3
#define ID_SAVE                         3
#define IDC_GOVIRTUAL                   3
#define IDC_CLEAR                       3
#define IDC_SPARE                       3
#define ID_NONE                         3
#define IDC_SET                         3
#define ID_CREATE                       4
#define IDC_DECOMMIT                    4
#define ID_ALL                          4
#define IDC_NEW_SURFACE2                4
#define IDC_EM_CENTER                   5
#define IDC_COMMITALL                   5
#define ID_CREATEFAST                   5
#define IDC_NEW_SURFACE3                5
#define IDC_COLLIDE                     6
#define IDC_TEST_MATERIAL               7
#define IDC_STOP_COLLIDE                7
#define IDD_GUIAPP_DIALOG               102
#define IDD_PLAYER                      107
#define BUTTON_BACK_TOFOGBACK           122
#define IDR_MAINFRAME                   128
#define MENU_TESTAPP                    129
#define IDD_ABOUT                       129
#define IDD_FLOATTOOLS                  130
#define IDD_CAMERA_PROPERTIES           131
#define IDD_LIGHT_PROPERTIES            132
#define IDD_BACKGROUND                  133
#define IDB_PALETTE                     134
#define IDD_FOG                         135
#define IDD_AUDIO_PROPERTIES            137
#define IDD_AUDIO_SOUNDATTRIB           138
#define IDD_OBJECT_PROPERTIES           139
#define IDD_GAMMA                       140
#define IDD_DIALOG_PHYSICS              141
#define IDD_PERSPECTIVE                 143
#define IDD_RENDERCACHE                 144
#define ICON_RAPTOR2                    146
#define ICON_TREX                       147
#define IDD_AUDIO_ENVIRONMENT           148
#define IDD_DUMMY                       149
#define IDD_TERRAIN                     150
#define IDD_DEPTHSORT_SETTINGS          151
#define IDD_EDITMATERIAL_DIALOG         152
#define IDD_SOUND_PROPERTIES            153
#define MENU_E3                         155
#define IDD_MIPMAP                      156
#define IDD_ALPHA_COLOUR                157
#define IDD_TEXTUREPACK                 162
#define IDD_DIALOG_MEMSTATS             163
#define IDD_PARTITION                   164
#define IDD_OCCLUDE                     165
#define IDD_STRING                      166
#define IDD_SKY                         167
#define IDD_GUN                         168
#define IDD_SCHEDULER                   169
#define IDD_VIRTUALMEM                  170
#define IDD_DIALOG_BUMPPACK             172
#define IDD_PARAMETER_DIALOG            173
#define IDD_AIDIALOGS2_DIALOG           174
#define IDD_DIALOG_PACKOPTIONS          175
#define IDD_MAGNET                      176
#define IDD_DIALOG_OBJECTCULLING        177
#define IDD_MATERIAL                    178
#define IDD_WATER                       179
#define IDD_QUALITY                     180
#define IDD_TELEPORT                    183
#define IDD_GORE                        184
#define IDC_STATIC_LIGHTTYPE            1000
#define IDC_SCROLL_CAM_ZOOM             1001
#define IDC_STATIC_ORIGINDISTANCE_START 1001
#define IDC_MSET_M2_LIST                1001
#define IDC_ACTIVITIES                  1001
#define IDC_SCROLL_CAM_ANGLE            1002
#define IDC_EDIT_COS_FULL               1002
#define IDC_REFWF_S1                    1002
#define IDC_SCROLL_CAM_NEAR             1003
#define IDC_EDIT_COS_ZERO               1003
#define IDC_REFWF_S2                    1003
#define IDC_SCROLL_CAM_FAR              1004
#define IDC_EDIT_FALLOFF                1004
#define IDC_MSET_LIST                   1004
#define IDC_STATIC_CAM_ZOOM             1005
#define IDC_STATIC_POINTDIR_START       1005
#define IDC_REFWF_S3                    1005
#define IDC_PARAMETER0                  1005
#define IDC_STATIC_CAM_ANGLE            1006
#define IDC_STATIC_LAST_START           1006
#define IDC_REFWF_S4                    1006
#define IDC_PARAMETER1                  1006
#define IDC_STATIC_CAM_NEAR             1007
#define IDC_SCROLL_RED                  1007
#define IDC_PARAMETER2                  1007
#define IDC_STATIC_CAM_FAR              1008
#define IDC_SCROLL_GREEN                1008
#define IDC_PARAMETER3                  1008
#define IDC_SCROLL_AMBIENT              1009
#define IDC_SCROLL_BLUE                 1009
#define IDC_PARAMETER4                  1009
#define IDC_STATIC_AMBIENT              1010
#define IDC_STATIC_RED                  1010
#define IDC_PARAMETER5                  1010
#define IDC_SCROLL_ORIGINDISTANCE       1011
#define IDC_STATIC_GREEN                1011
#define IDC_PARAMETER6                  1011
#define IDC_BUTTON_ADDOBJECT            1012
#define IDC_STATIC_ORIGINDISTANCE       1012
#define IDC_STATIC_BLUE                 1012
#define IDC_PARAMETER7                  1012
#define IDC_BUTTON_DELETE               1013
#define IDC_CHECK_GRAYSCALE             1013
#define IDC_REFWF_BROWSE_S1             1013
#define IDC_STATIC_PARAMETER1           1013
#define IDC_BUTTON_EDIT                 1014
#define IDC_SCROLL_FOGCONSTANT          1014
#define IDC_REFWF_BROWSE_S2             1014
#define IDC_STATIC_PARAMETER2           1014
#define IDC_BUTTON_ADDDIRLIGHT          1015
#define IDC_SCROLL_FOGPOWER             1015
#define IDC_REFWF_BROWSE_S3             1015
#define IDC_STATIC_PARAMETER3           1015
#define IDC_BUTTON_ADDPTLIGHT           1016
#define IDC_REFWF_BROWSE_S4             1016
#define IDC_STATIC_PARAMETER4           1016
#define IDC_BUTTON_ADDPTDIRLIGHT        1017
#define IDC_STATIC_FOGCONSTANT          1017
#define IDC_REFWF_TEST_S1               1017
#define IDC_STATIC_PARAMETER5           1017
#define IDC_BUTTON_EDITAMBIENT          1018
#define IDC_STATIC_FOGPOWER             1018
#define IDC_REFWF_TEST_S2               1018
#define IDC_STATIC_PARAMETER6           1018
#define IDC_BUTTON_EDITCAMERA           1019
#define IDC_REFWF_TEST_S3               1019
#define IDC_STATIC_PARAMETER7           1019
#define IDC_RADIO_MOVE                  1020
#define IDC_REFWF_TEST_S4               1020
#define IDC_STATIC_PARAMETER8           1020
#define IDC_RADIO_OBJECT                1021
#define IDC_EDIT_PARAMETER1             1021
#define id1                             1022
#define IDC_EDIT_PARAMETER2             1022
#define id2                             1023
#define IDC_EDIT_PARAMETER3             1023
#define id3                             1024
#define IDC_EDIT_PARAMETER4             1024
#define id4                             1025
#define IDC_EDIT_PARAMETER5             1025
#define IDC_EDIT_PARAMETER6             1026
#define IDC_AU_CREATE_ATTENUATE         1027
#define IDC_EDIT_PARAMETER7             1027
#define IDC_AU_CREATE_SPATIALIZE        1028
#define IDC_EDIT_PARAMETER8             1028
#define IDC_AU_CREATE_DOPPLER           1029
#define IDC_PARAMETER8                  1029
#define IDC_AU_CREATE_REVERB            1030
#define IDC_STATIC_PARAMETER9           1030
#define IDC_AU_CPU_NONE                 1031
#define IDC_MSET_M1_LIST                1031
#define IDC_EDIT_PARAMETER0             1031
#define IDC_AU_CPU_LOW                  1032
#define IDC_M2TOM1                      1032
#define IDC_AU_CPU_MEDIUM               1033
#define IDC_AU_REVERB_USE               1034
#define IDC_M1TOM2                      1034
#define IDC_MATERIALNAME                1036
#define IDC_AU_TREE_OBJLIST             1039
#define IDC_AU_SPEEDSOUND_SB            1042
#define IDC_AU_REVERB_DECAY_TEXT        1043
#define IDC_AU_REVERB_INTENSITY_TEXT    1044
#define IDC_AU_SPEEDSOUND_TEXT          1045
#define IDC_AEA_PRIORITY_TEXT           1045
#define IDC_AU_REVERB_INTENSITY_SB      1046
#define IDC_AU_REVERB_DECAY_SB          1047
#define IDC_AU_TREE_OBJLIST_EDIT        1048
#define IDC_AEA_PRIORITY_SB             1048
#define IDC_GRAPH_VOL                   1048
#define IDC_GRAPH_PIT                   1049
#define IDC_SM_SLIDER1                  1050
#define IDC_VOL_SLOPE_TEXT              1051
#define IDC_SM_SLIDER2                  1052
#define IDC_VOL_INTS_TEXT               1053
#define IDC_SOUND_INTENSITY_TEXT        1054
#define IDC_SM_SLIDER3                  1054
#define IDC_SOUND_PITCHADJ_TEXT         1055
#define IDC_VOL_MIN_TEXT                1055
#define IDC_SM_SLIDER4                  1056
#define IDC_VOL_MAX_TEXT                1057
#define IDC_SM_SLIDER5                  1058
#define IDC_SOUND_MINBACK               1059
#define IDC_PIT_SLOPE_TEXT              1059
#define IDC_SOUND_MAXBACK               1060
#define IDC_SM_SLIDER6                  1060
#define IDC_SOUND_MINFRONT              1061
#define IDC_PIT_INTS_TEXT               1061
#define IDC_SOUND_MAXFRONT              1062
#define IDC_SM_SLIDER7                  1062
#define IDC_SOUND_INTENSITY_SB          1063
#define IDC_PIT_MIN_TEXT                1063
#define IDC_SOUND_ADDSOUND              1064
#define IDC_SOUND_PITCHADJ_SB           1064
#define IDC_SM_SLIDER8                  1064
#define IDC_RADIO_LINEAR                1065
#define IDC_PIT_MAX_TEXT                1065
#define IDC_RADIO_INVERSE               1066
#define IDC_STATIC_NAME                 1066
#define IDC_RADIO_EXPONENTIAL           1067
#define IDC_STATIC_TYPE                 1067
#define IDC_SM_SLIDER9                  1067
#define IDC_STATIC_FACES                1068
#define IDC_SM_RADIO1                   1068
#define IDC_STATIC_VERTICES             1069
#define IDC_SM_RADIO2                   1069
#define IDC_STATIC_PHYSICS_TYPE         1070
#define IDC_SM_RADIO3                   1070
#define IDC_STATIC_PHYSICS_BV           1071
#define IDC_SM_RADIO4                   1071
#define IDC_PHYSICS_BV_DIM_X            1072
#define IDC_SM_SLIDER10                 1072
#define IDC_PHYSICS_BV_DIM_Y            1073
#define IDC_TEST_VEL_TEXT               1073
#define IDC_TEST_VELOCITY_TEXT          1073
#define IDC_PHYSICS_BV_DIM_Z            1074
#define IDC_CUT_VEL_TEXT                1074
#define IDC_PHYSICS_BV_POS_X            1075
#define IDC_DUAL_CHECK                  1075
#define IDC_PHYSICS_BV_POS_Y            1076
#define IDC_SM_SLIDER11                 1076
#define IDC_PHYSICS_BV_POS_Z            1077
#define IDC_SM_SLIDER12                 1077
#define IDC_PHYSICS_SOUND_MATERIAL      1078
#define IDC_SM_SLIDER14                 1078
#define IDC_PHYSICS_FLAGS               1079
#define IDC_SM_SLIDER13                 1079
#define IDC_PHYSICS_BOX_DENSITY         1080
#define IDC_SCROLL_GAMMA                1080
#define IDC_SCROLL_GORE                 1080
#define IDC_WORLD_SCALE_TEXT            1080
#define IDC_PHYSICS_BOX_ELASTICITY      1081
#define IDC_STATIC_GAMMA                1081
#define IDC_STATIC_GORE                 1081
#define IDC_ATTENUATE_TEXT              1081
#define IDC_PHYSICS_BOX_FRICTION        1082
#define IDC_ENABLE_GAMMA                1082
#define IDC_GRAPH_WORLD                 1082
#define IDC_STATIC_PHYSICS_LABEL_0      1083
#define IDC_STATIC_POINTS               1083
#define IDC_WORLD_POS_TEXT              1083
#define IDC_SCROLL_MIN_AMBIENT          1083
#define IDC_STATIC_PHYSICS_LABEL_1      1084
#define IDC_STATIC_TRIANGLES            1084
#define IDC_TRANSFER                    1084
#define IDC_STATIC_PHYSICS_LABEL_2      1085
#define IDC_PHYSICS_BOX_MASS            1085
#define IDC_COLLISION_ENABLE            1085
#define IDC_STATIC_PHYSICS_LABEL_3      1086
#define IDC_SLIDE_ENABLE                1086
#define IDC_STATIC_PHYSICS_LABEL_4      1087
#define IDC_STATIC_PHYSICS_LABEL_5      1088
#define IDC_STATIC_PHYSICS_LABEL_6      1089
#define IDC_STATIC_PHYSICS_LABEL_7      1090
#define IDC_PRES_POS_X                  1091
#define IDC_STATIC_PHYSICS_LABEL_8      1091
#define IDC_STATIC2                     1091
#define IDC_PRES_POS_Y                  1092
#define IDC_STATIC_PHYSICS_LABEL_9      1092
#define IDC_STATIC1                     1092
#define IDC_PRES_POS_Z                  1093
#define IDC_STATIC_PHYSICS_LABEL_10     1093
#define IDC_COMBO1                      1093
#define IDC_PRES_ROT_X                  1094
#define IDC_STATIC_PHYSICS_LABEL_11     1094
#define IDC_COMBO2                      1094
#define IDC_STATIC_PHYSICS_LABEL_12     1095
#define IDC_COMBO3                      1095
#define IDC_STATIC_PHYSICS_LABEL_13     1096
#define IDC_PRES_SCALE                  1097
#define IDC_STATIC_PHYSICS_LABEL_14     1097
#define IDC_STATIC_PHYSICS_LABEL_15     1098
#define IDC_PRES_DISTANCE               1098
#define IDC_STATIC_PHYSICS_LABEL_16     1099
#define IDC_STATIC_PHYSICS_LABEL_17     1100
#define IDC_STATIC_PHYSICS_LABEL_18     1101
#define IDC_STATIC_PHYSICS_LABEL_19     1102
#define IDC_SCROLL_PHYSICS_0            1103
#define IDC_SCROLL_PHYSICS_1            1104
#define IDC_SCROLL_PHYSICS_2            1105
#define IDC_SCROLL_PHYSICS_3            1106
#define IDC_SCROLL_PHYSICS_4            1107
#define IDC_SCROLL_PHYSICS_5            1108
#define IDC_SCROLL_PHYSICS_6            1109
#define IDC_SCROLL_PHYSICS_7            1110
#define IDC_SCROLL_PHYSICS_8            1111
#define IDC_SCROLL_PHYSICS_9            1112
#define IDC_SCROLL_PHYSICS_10           1113
#define IDC_SCROLL_PHYSICS_11           1114
#define IDC_SCROLL_PHYSICS_12           1115
#define IDC_SCROLL_PHYSICS_13           1116
#define IDC_SCROLL_PHYSICS_14           1117
#define IDC_SCROLL_PHYSICS_15           1118
#define IDC_SCROLL_PHYSICS_16           1119
#define IDC_SCROLL_PHYSICS_17           1120
#define IDC_SCROLL_PHYSICS_18           1121
#define IDC_SCROLL_PHYSICS_19           1122
#define IDC_STATIC_PHYSICS_VALUE_0      1123
#define IDC_STATIC_PHYSICS_VALUE_1      1124
#define IDC_SCROLL_PERSPECTIVE_ERROR    1124
#define IDC_STATIC_PHYSICS_VALUE_2      1125
#define IDC_SCROLL_PERSPECTIVE_SUBDIVIDE 1125
#define IDC_STATIC_PHYSICS_VALUE_3      1126
#define IDC_STATIC_PERSPECTIVE_ERROR    1126
#define IDC_STATIC_PHYSICS_VALUE_4      1127
#define IDC_STATIC_PERSPECTIVE_SUBDIVIDE 1127
#define IDC_STATIC_PHYSICS_VALUE_5      1128
#define IDC_SCROLL_INVZDX               1128
#define IDC_STATIC_PHYSICS_VALUE_6      1129
#define IDC_SCROLL_MAX_RESIZE           1129
#define IDC_STATIC_INVZDX               1129
#define IDC_STATIC_PHYSICS_VALUE_7      1130
#define IDC_SCROLL_SIZERATIO            1130
#define IDC_SCROLL_PERSPECTIVE_ERROR2   1130
#define IDC_STATIC_PHYSICS_VALUE_8      1131
#define IDC_SCROLL_ANGULARERROR         1131
#define IDC_SCROLL_MINDISTANCE          1131
#define IDC_SCROLL_PERSPECTIVE_SUBDIVIDE2 1131
#define IDC_STATIC_PHYSICS_VALUE_9      1132
#define IDC_STATIC_MAX_RESIZE           1132
#define IDC_STATIC_PERSPECTIVE_ERROR2   1132
#define IDC_STATIC_PHYSICS_VALUE_10     1133
#define IDC_STATIC_SIZERATIO            1133
#define IDC_STATIC_PERSPECTIVE_SUBDIVIDE2 1133
#define IDC_STATIC_PHYSICS_VALUE_11     1134
#define IDC_STATIC_ANGULARERROR         1134
#define IDC_STATIC_MINDISTANCE          1134
#define IDC_SCROLL_PERSPECTIVE_MINSUBDIVIDE 1134
#define IDC_STATIC_PHYSICS_VALUE_12     1135
#define IDC_SCROLL_MIN_RESIZE           1135
#define IDC_STATIC_PERSPECTIVE_MINSUBDIVIDE 1135
#define IDC_STATIC_PHYSICS_VALUE_13     1136
#define IDC_STATIC_MIN_RESIZE           1136
#define IDC_SCROLL_PERSPECTIVE_MAXSUBDIVIDE 1136
#define IDC_STATIC_PHYSICS_VALUE_14     1137
#define IDC_AEA_REVERB_INTENSITY_SB     1137
#define IDC_STATIC_PERSPECTIVE_MAXSUBDIVIDE 1137
#define IDC_STATIC_PHYSICS_VALUE_15     1138
#define IDC_AEA_REVERB_DECAY_SB         1138
#define IDC_SCROLL_PERSPECTIVE_INVZFORMAX 1138
#define IDC_STATIC_PHYSICS_VALUE_16     1139
#define IDC_SCROLL_RADIUSTODISTANCE     1139
#define IDC_AEA_REVERB_USE              1139
#define IDC_SCROLL_SPHEREDEG            1139
#define IDC_STATIC_PERSPECTIVE_INVZFORMAX 1139
#define IDC_STATIC_PHYSICS_VALUE_17     1140
#define IDC_STATIC_RADIUSTODISTANCE     1140
#define IDC_AEA_CPU_MEDIUM              1140
#define IDC_STATIC_SPHEREDEG            1140
#define IDC_SCROLL_PERSPECTIVE_INVZSCALE 1140
#define IDC_STATIC_PHYSICS_VALUE_18     1141
#define IDC_SCROLL_MINPIXEL             1141
#define IDC_AEA_CPU_LOW                 1141
#define IDC_STATIC_PERSPECTIVE_INVZSCALE 1141
#define IDC_STATIC_PHYSICS_VALUE_19     1142
#define IDC_STATIC_MINPIXEL             1142
#define IDC_AEA_CPU_NONE                1142
#define IDC_STATIC_PERCENTTRIANGLES     1143
#define IDC_AEA_REVERB_DECAY_TEXT       1143
#define IDC_SCROLL_CYLINDERDEG          1143
#define IDC_AEA_REVERB_INTENSITY_TEXT   1144
#define IDC_STATIC_CYLINDERDEG          1144
#define IDC_SCROLL_TERRAIN_ERROR        1145
#define IDC_STATIC_TERRAIN_ERROR        1146
#define IDC_SCROLL_NEARTOL              1147
#define IDC_SCROLL_TERRAIN_MAX_REFINE_DIST 1147
#define IDC_SCROLL_FARTOL               1148
#define IDC_STATIC_TERRAIN_ERROR2       1148
#define IDC_STATIC_TERRAIN_MAX_REF_DIST 1148
#define IDC_SCROLL_NEARZ                1149
#define IDC_SCROLL_TERRAIN_FREQ_RANGE   1149
#define IDC_SCROLL_TERRAIN_MEDIUM_FREQ_RESPONSE 1149
#define IDC_SCROLL_VOLUMEDEG            1149
#define IDC_STATIC_EUTHANASIA           1150
#define IDC_STATIC_FARZ_NO              1150
#define IDC_SCROLL_TERRAIN_FAR_FREQ_RESPONSE 1150
#define IDC_SCROLL_EUTHANASIA           1151
#define IDC_SCROLL_FARZ                 1151
#define IDC_SCROLL_TERRAIN_DISTANCE_RELAX 1151
#define IDC_SCROLL_TERRAIN_TEXEL_X_RES  1151
#define IDC_SCROLL_TERRAIN_TEX_M        1151
#define IDC_SCROLL_FARZ_NO              1152
#define IDC_STATIC_TERRAIN_ERROR4       1152
#define IDC_STATIC_TERRAIN_DIST_RELAX   1152
#define IDC_SCROLL_DETAILREDUCE         1152
#define IDC_SCROLL_TERRAIN_TEXEL_Y_RES  1152
#define IDC_SCROLL_TERRAIN_DIST_MUL     1152
#define IDC_STATIC_FARZ                 1153
#define IDC_SCROLL_TERRAIN_MAX_REFINE_RANGE 1153
#define IDC_STATIC_DETAILREDUCE         1153
#define IDC_STATIC_NEARZ                1154
#define IDC_STATIC_TERRAIN_MAX_REFINE_RANGE 1154
#define IDC_SCROLL_MAXMESHES            1154
#define IDC_STATIC_VOLUMEDEG            1154
#define IDC_STATIC_FARTOL               1155
#define IDC_STATIC_MAXMESHES            1155
#define IDC_SCROLL_TERRAIN_QUANTISATION_BITS 1155
#define IDC_SCROLL_SMOOTHQUALITY        1155
#define IDC_SCROLL_DISTORTION           1155
#define IDC_STATIC_NEARTOL              1156
#define IDC_SCROLL_AREA                 1156
#define IDC_STATIC_TERRAIN_QUANTISATION_BITS 1156
#define IDC_SCROLL_PIXELTOL             1157
#define IDC_SCROLL_TERRAIN_MEDIUM_RANGE 1157
#define IDC_STATIC_AREA                 1157
#define IDC_SCROLL_TERRAIN_FREQ_CUTOFF  1157
#define ID_RADIO_LINEAR                 1158
#define IDC_STATIC_TERRAIN_MEDIUM_RANGE 1158
#define IDC_SCROLL_LINE                 1158
#define IDC_STATIC_TERRAIN_FREQ_CUTOFF  1158
#define ID_RADIO_INVERSE                1159
#define IDC_SLIDER1                     1159
#define IDC_STATIC_LINE                 1159
#define IDC_SCROLL_TERRAIN_MIN_SIZE     1159
#define IDC_STATIC_PIXELTOL             1160
#define IDC_CHECK1                      1160
#define IDC_AUDIO_ENABLE                1160
#define IDC_SCROLL_POLYAREA             1160
#define IDC_CHECK_USE_PREBUILT          1160
#define IDC_SLIDER2                     1160
#define IDC_SCROLL_TERRAIN_DIST_TEX     1160
#define IDC_SCROLL_MAXNUM               1161
#define IDC_CHECK2                      1161
#define IDC_STATIC_POLYAREA             1161
#define IDC_SLIDER3                     1161
#define IDC_SCROLL_TERRAIN_DIST_SHAD    1161
#define IDC_STATIC_MAXNUM               1162
#define IDC_SOUND_MONO                  1162
#define IDC_SLIDER4                     1162
#define IDC_SCROLL_TERRAIN_DIST_MOVE    1162
#define IDC_CHECK6                      1162
#define IDC_SOUND_STEREO                1163
#define IDC_SCROLL_NEARTOL_TERRAIN      1163
#define IDC_SLIDER5                     1163
#define IDC_SCROLL_SAMPLEDISTORTION     1163
#define IDC_SCROLL_OVERSAMPLING         1163
#define IDC_SCROLL_TERRAIN_LIFETIME     1163
#define IDC_SOUND_8BIT                  1164
#define IDC_STATIC_NEARTOL_TERRAIN      1164
#define IDC_SLIDER6                     1164
#define IDC_SCROLL_TURNSPEED            1164
#define IDC_SCROLL_TERRAIN_TEX_PIX      1164
#define IDC_SOUND_16BIT                 1165
#define IDC_SCROLL_TERRAIN_MEDIUM_TOLERANCE 1165
#define IDC_SCROLL_FARTOL_TERRAIN       1165
#define IDC_SLIDER7                     1165
#define IDC_SCROLL_UNDERSAMPLING        1165
#define IDC_SCROLL_TERRAIN_PIX_TOLERANCE_START 1165
#define IDC_TEXT_FREQ                   1166
#define IDC_STATIC_TERRAIN_MEDIUM_TOLERANCE 1166
#define IDC_STATIC_FARTOL_TERRAIN       1166
#define IDC_SCROLL_VOLUMETHRESHOLD      1166
#define IDC_STATIC_TERRAIN_PIX_TOLERANCE_START 1166
#define IDC_SCROLL_TERRAIN_FAR_TOLERANCE 1167
#define IDC_SCROLL_NEARZ_TERRAIN        1167
#define IDC_CHECK3                      1167
#define IDC_SCROLL_MAXOBJECTS           1167
#define IDC_SCROLL_TERRAIN_DEFER_EVAL   1167
#define IDC_STATIC_TERRAIN_FAR_TOLERANCE 1168
#define IDC_STATIC_NEARZ_TERRAIN        1168
#define IDC_CHECK4                      1168
#define IDC_SCROLL_AREAEFFICIENCY       1168
#define IDC_STATIC_TERRAIN_DEFER_EVAL   1168
#define ID_STATIC_TERRAIN_FREQ          1169
#define IDC_STATIC_TERRAIN_FREQ         1169
#define IDC_STATIC_TERRAIN_MEDIUM_FREQ_RESPONSE 1169
#define IDC_SCROLL_FARZ_TERRAIN         1169
#define IDC_CHECK5                      1169
#define IDC_SCROLL_TERRAIN_WIREZOOM     1169
#define IDC_SCROLL_PARALLAXSHEAR        1169
#define IDC_STATIC_TERRAIN_FAR_FREQ_RESPONSE 1170
#define IDC_CHECK_SCHEDULE              1170
#define IDC_STATIC_FARZ_TERRAIN         1170
#define IDC_SPEAKER_QUAD                1170
#define IDC_STATIC_TERRAIN_WIREZOOM     1170
#define IDC_SCROLL_TERRAIN_MEDIUM_TOLERANCE_RELAX 1171
#define IDC_CHECK_ADAPTIVE              1171
#define IDC_CHECK_PREDICTION            1171
#define IDC_SPEAKER_SURROUND            1171
#define IDC_SCROLL_BINARYAT             1171
#define IDC_SCROLL_TERRAIN_PIX_TOLERANCE_END 1171
#define IDC_STATIC_TERRAIN_MEDIUM_TOLERANCE_RELAX 1172
#define IDC_LOCAL_PROC                  1172
#define IDC_SPEAKER_PHONES              1172
#define IDC_STATIC_BINARYAT             1172
#define IDC_STATIC_TERRAIN_PIX_TOLERANCE_END 1172
#define IDC_CHECK_FORCECACHING          1172
#define IDC_SCROLL_TERRAIN_FAR_TOLERANCE_RELAX 1173
#define IDC_CHECK_TERRAIN               1173
#define IDC_SPEAKER_STEREO              1173
#define IDC_SCROLL_TERRAIN_MAX_DIST_RATIO 1173
#define IDC_STATIC_TERRAIN_FAR_TOLERANCE_RELAX 1174
#define IDC_STATIC_MIP_THRESHOLD        1174
#define IDC_SPEAKER_MONO                1174
#define IDC_SCROLL_QUADAT               1174
#define IDC_STATIC_TERRAIN_MAX_DIST_RATIO 1174
#define IDC_STATIC_TERRAIN_TEXEL_X_RES  1175
#define IDC_SCROLL_MIP_THRESHOLD        1175
#define IDC_STATIC_TERRAIN_TEX_M        1175
#define IDC_STATIC_QUADAT               1175
#define IDC_CHECK7                      1175
#define IDC_SCROLL_TERRAIN_MIN_NODE_SIZE 1175
#define IDC_STATIC_TERRAIN_TEXEL_Y_RES  1176
#define IDC_SCROLL_COLOUR               1176
#define IDC_STATIC_TERRAIN_TEX_PIX      1176
#define IDC_STATIC_TERRAIN_MIN_NODE_SIZE 1176
#define IDC_SLIDER8                     1176
#define IDC_STATIC_COLOUR               1177
#define IDC_SCROLL_TERRAIN_TRI_NODE_DIFF_SHIFT 1177
#define IDC_SLIDER9                     1177
#define IDC_BUTTON_VIEW                 1178
#define IDC_STATIC_TERRAIN_MIN_SIZE     1178
#define IDC_STATIC_TERRAIN_TRI_NODE_DIFF_SHIFT 1178
#define IDC_SCROLL_TERRAIN_TEXEL_SCALE_START 1179
#define IDC_STATIC_TERRAIN_TEXEL_SCALE_START 1180
#define IDC_SCROLL_TERRAIN_TEXEL_SCALE_END 1181
#define IDC_STATIC_TERRAIN_TEXEL_SCALE_END 1182
#define IDC_SCROLL_TERRAIN_DISABLE_SHADOW_DIST 1183
#define IDC_SCROLL_BLEND                1184
#define IDC_TEXTURE_BOX                 1184
#define IDC_STATIC_TERRAIN_DISABLE_SHADOW_DIST 1184
#define IDC_STATIC_BLEND                1185
#define IDC_SCROLL_TERRAIN_DISABLE_TEXTURE_DIST 1185
#define IDC_LOG_LIST                    1186
#define IDC_STATIC_TERRAIN_DISABLE_TEXTURE_DIST 1186
#define IDC_REMAINING                   1187
#define IDC_PERCENT_DONE                1188
#define IDC_SCROLL_OCCLUDE_THRESHOLD    1189
#define IDC_SCROLL_TERRAIN_DISABLE_DYNAMIC_TEXTURE_DIST 1189
#define IDC_ACTION                      1190
#define IDC_STATIC_OCCLUDE_THRESHOLD    1190
#define IDC_STATIC_TERRAIN_DISABLE_DYNAMIC_TEXTURE_DIST 1190
#define IDC_TEXT1                       1191
#define IDC_SCROLL_OCCLUDE_MAXINVIEW    1191
#define IDC_STATIC_OCCLUDE_MAXINVIEW    1192
#define IDC_TEXT4                       1192
#define IDC_TEXT2                       1193
#define IDC_TEXT3                       1194
#define IDC_TEXT5                       1195
#define IDC_TEXT6                       1196
#define IDC_TEXT7                       1197
#define IDC_STATIC_GUN_EXTENSION        1198
#define IDC_STATIC_GUN_MOMENT           1199
#define IDC_SCROLL_GUN_EXTENSION        1200
#define IDC_SCROLL_GUN_MOMENT           1201
#define IDC_STATIC_TIME                 1201
#define IDC_SCROLL_SCHEDULER            1202
#define IDC_A3D_HARDWARE                1204
#define IDC_RADIO1                      1205
#define IDC_RADIOA                      1205
#define IDC_STATIC_TIME_TERRAIN         1205
#define IDC_STATIC_GUN_EXTENSION_PULL   1206
#define IDC_RADIO2                      1206
#define IDC_RADIOE                      1206
#define IDC_SCROLL_SCHEDULER_TERRAIN    1206
#define IDC_STATIC_GUN_IMPULSE_PULL     1207
#define IDC_RADIO3                      1207
#define IDC_RADIOB                      1207
#define IDC_STATIC_SCHEDULER_THRESHOLD  1207
#define IDC_SCROLL_GUN_EXTENSION_PULL   1208
#define IDC_RADIO4                      1208
#define IDC_RADIOC                      1208
#define IDC_SCROLL_SCHEDULER_THRESHOLD  1208
#define IDC_SCROLL_GUN_IMPULSE_PULL     1209
#define IDC_RADIO5                      1209
#define IDC_RADIOD                      1209
#define IDC_RADIO6                      1210
#define IDC_RADIOF                      1210
#define IDC_RADIO7                      1211
#define IDC_RADIOG                      1211
#define IDC_RADIO8                      1212
#define IDC_RADIOH                      1212
#define IDC_VM_COUNT                    1213
#define IDC_RADIO9                      1213
#define IDC_STATIC_SMOOTHQUALITY        1214
#define IDC_STATIC_DISTORTION           1214
#define IDC_RADIO10                     1214
#define IDC_STATIC_SAMPLEDISTORTION     1215
#define IDC_CHECK_NONVISIBLE            1215
#define IDC_STATIC_DESCRIPTION          1215
#define IDC_RADIO11                     1215
#define IDC_STATIC_OVERSAMPLING         1216
#define IDC_MAP0                        1216
#define IDC_RADIO12                     1216
#define IDC_STATIC_TURNSPEED            1217
#define IDC_MAP1                        1217
#define IDC_RADIO13                     1217
#define IDC_STATIC_UNDERSAMPLING        1218
#define IDC_MAP2                        1218
#define IDC_RADIO14                     1218
#define IDC_STATIC_VOLUMETHRESHOLD      1219
#define IDC_MAP3                        1219
#define IDC_RADIO15                     1219
#define IDC_STATIC_MAXOBJECTS           1220
#define IDC_MAP4                        1220
#define IDC_RADIO16                     1220
#define IDC_CHECK_LOWRES                1221
#define IDC_MAP5                        1221
#define IDC_STATIC_PARALLAXSHEAR        1221
#define IDC_RADIO17                     1221
#define IDC_STATIC_AREAEFFICIENCY       1222
#define IDC_MAP6                        1222
#define IDC_RADIO18                     1222
#define IDC_MAP7                        1223
#define IDC_RADIO19                     1223
#define IDC_SCROLLBAR1                  1224
#define IDC_RADIO20                     1224
#define IDC_LIST1                       1226
#define IDC_TEXT_XSIZE                  1227
#define IDC_TEXT_YSIZE                  1228
#define IDC_RADIO21                     1228
#define IDC_TEXT_MIPLEVEL               1229
#define IDC_RADIO22                     1229
#define IDC_TEXT_PACKED                 1230
#define IDC_RADIO23                     1230
#define IDC_TEXT_CURVED                 1231
#define IDC_RADIO24                     1231
#define IDC_TEXT_MAXIMUM                1232
#define IDC_RADIO25                     1232
#define IDC_TEXT_MINIMUM                1233
#define IDC_RADIO26                     1233
#define IDC_PACK_FRAME                  1234
#define IDC_STATE                       1235
#define IDC_UP                          1236
#define IDC_DOWN                        1237
#define IDC_LEFT                        1238
#define IDC_RIGHT                       1239
#define IDC_TEXT_POSITION               1240
#define IDC_TEXT_XSIZE2                 1241
#define IDC_TEXT_MIP                    1241
#define IDC_TEXT_MIP_DIFF               1242
#define IDC_STATIC_TERRAIN_DIST_MUL     1243
#define IDC_STATIC_TERRAIN_DIST_TEX     1244
#define IDC_STATIC_TERRAIN_DIST_SHAD    1245
#define IDC_STATIC_TERRAIN_DIST_MOVE    1246
#define IDC_STATIC_TERRAIN_LIFETIME     1247
#define IDC_CHECK_TERRAIN_MULTI         1251
#define IDC_CHECK_TERRAIN_ORIENT        1252
#define IDC_HOTKEY1                     1253
#define IDC_CHECK_TERRAIN_DIST          1253
#define IDC_CHECK_TERRAIN_DYNAMIC       1254
#define ID_AI_TEXT                      1254
#define IDC_CHECK_TERRAIN_PURGE_DIST    1255
#define IDC_EDIT_MASTER                 1255
#define IDC_CHECK_TERRAIN_CLEARS        1255
#define IDC_CHECK_TERRAIN_TRI           1256
#define IDC_EDIT_SLAVE                  1256
#define IDC_CHECK_TERRAIN_FREQ_AS_RATIO 1256
#define IDC_CHECK_TERRAIN_TEX_STATIC    1257
#define IDC_CHECK_XFREE                 1257
#define IDC_CHECK_TERRAIN_FREEZE        1257
#define IDC_CHECK_TERRAIN_WIRETRIS      1258
#define IDC_CHECK_YFREE                 1258
#define IDC_CHECK_TERRAIN_WIREQUADS     1259
#define IDC_CHECK_ZFREE                 1259
#define IDC_CHECK_PICKUP                1260
#define IDC_CHECK_TERRAIN_SHOW_CONSTRAINED 1260
#define IDC_CHECK_ORIENT                1261
#define IDC_CHECK_TERRAIN_REGION_UPLOADS 1261
#define IDC_CHECK_BREAKABLE             1262
#define IDC_CHECK_TERRAIN_PROJ_NEAREST  1262
#define IDC_EDIT_MAG_STRENGTH           1263
#define IDC_CHECK_TERRAIN_CONFORM_CONSTRAINT 1263
#define IDC_SUBTITLE_TOP                1264
#define IDC_CHECK_LIMITS                1264
#define IDC_SUBTITLE_BOTTOM             1265
#define IDC_CHECK_XTFREE                1265
#define IDC_SUB_SIZE1                   1266
#define IDC_CHECK_YTFREE                1266
#define IDC_SUB_SIZE2                   1267
#define IDC_CHECK_ZTFREE                1267
#define IDC_SUB_SIZE3                   1268
#define IDC_SUB_SYSMEM                  1269
#define IDC_SCROLL_CULLING              1270
#define IDC_STATIC_CULLING              1271
#define IDC_CHECK_FASTERPHYSICS         1272
#define IDC_SCROLL_CULLINGSHADOW        1272
#define IDC_STATIC_ABOUT_DATE           1273
#define IDC_STATIC_CULLINGSHADOW        1273
#define IDC_STATIC_ABOUT_VERSION        1274
#define IDC_SCROLL_RADIUS               1274
#define IDC_STATIC_RADIUS               1275
#define IDC_SCROLL_RADIUSSHADOW         1278
#define IDC_STATIC_RADIUSSHADOW         1279
#define IDC_SCROLL_PRIORITY             1280
#define IDC_STATIC_PRIORITY             1281
#define IDC_OK                          1291
#define IDC_SPIN_HEAD_Z                 1295
#define IDC_EDIT18                      1296
#define IDC_SPIN_HEAD_Y                 1297
#define IDC_EDIT19                      1298
#define IDC_SPIN_HEAD_X                 1299
#define IDC_EDIT20                      1300
#define IDC_CHECK_HAND_ACTUAL           1301
#define IDC_CHECK_HEAD_ACTUAL           1302
#define IDC_EDIT24                      1303
#define IDC_EDIT1                       1304
#define IDC_SPIN_HAND_PICKUP_DIST       1305
#define IDC_TELE_Y                      1305
#define IDC_CHECK_CENTRE_EMPTY          1306
#define IDC_TELE_Z                      1306
#define IDC_SPIN_HAND_OFFSET_Z          1307
#define IDC_EDIT21                      1308
#define IDC_SPIN_HAND_OFFSET_Y          1309
#define IDC_EDIT22                      1310
#define IDC_SPIN_HAND_OFFSET_X          1311
#define IDC_EDIT23                      1312
#define IDC_CHECK_CENTRE_HOLDING        1312
#define IDC_EDIT17                      1313
#define IDC_CHECK_ALLOW_DROP            1314
#define IDC_SPIN_HAND_RANGE_MAX         1315
#define IDC_EDIT25                      1316
#define IDC_SPIN_HAND_RANGE_MIN         1317
#define IDC_EDIT26                      1318
#define IDC_EDIT2                       1319
#define IDC_SPIN_HAND_ROT_X_MIN         1320
#define IDC_SPIN_HAND_REACH_WIDTH       1321
#define IDC_EDIT28                      1322
#define IDC_SPIN_HAND_REACH_DIST        1323
#define IDC_EDIT29                      1324
#define IDC_EDIT3                       1325
#define IDC_SPIN_HAND_ROT_X_MAX         1326
#define IDC_SPIN_HAND_BODY_MAX_Y        1327
#define IDC_EDIT31                      1328
#define IDC_SPIN_HAND_BODY_MAX_X        1329
#define IDC_EDIT32                      1330
#define IDC_EDIT4                       1331
#define IDC_SPIN_HAND_ROT_Y_MIN         1332
#define IDC_SPIN_HAND_VIEW_X_MAX        1333
#define IDC_EDIT34                      1334
#define IDC_SPIN_HAND_VIEW_X_MIN        1335
#define IDC_EDIT35                      1336
#define IDC_EDIT5                       1337
#define IDC_SPIN_HAND_ROT_Y_MAX         1338
#define IDC_SPIN_HAND_VIEW_Y_MAX        1339
#define IDC_EDIT37                      1340
#define IDC_SPIN_HAND_VIEW_Y_MIN        1341
#define IDC_EDIT38                      1342
#define IDC_EDIT6                       1343
#define IDC_SPIN_DIFFUSE                1344
#define IDC_SPIN_FLAIL_VELOCITY         1344
#define IDC_SPIN_HEAD_BODY_Y_MAX        1345
#define IDC_SPIN_SPECULAR               1345
#define IDC_EDIT40                      1346
#define IDC_SPIN_ANGLE                  1346
#define IDC_SPIN_HEAD_BODY_X_MAX        1347
#define IDC_SPIN_EMISSIVE               1347
#define IDC_EDIT41                      1348
#define IDC_EDIT7                       1349
#define IDC_CHECK_REVERSE_THROW         1349
#define IDC_SPIN_MATERIAL_INDEX         1350
#define IDC_EDIT8                       1350
#define IDC_SPIN_THROW_TORQUE           1351
#define IDC_SPIN_NECK_X                 1352
#define IDC_SPIN_HEAD_TURN_X            1353
#define IDC_CHECK_BUMP                  1353
#define IDC_EDIT44                      1354
#define IDC_SPIN_HEAD_FOLLOW            1355
#define IDC_EDIT_TEXTURE                1355
#define IDC_EDIT45                      1356
#define IDC_CHECK_TEXTURE               1357
#define IDC_EDIT27                      1357
#define IDC_CHECK_TRANSPARENT           1358
#define IDC_SPIN_NECK_Y                 1358
#define IDC_STATIC_TEX_COUNT            1359
#define IDC_EDIT30                      1359
#define IDC_CHECK_ALPHA                 1360
#define IDC_SPIN_NECK_Z                 1360
#define IDC_CHECK_COPY                  1361
#define IDC_CHECK_AUTO_CROTCH_NORMAL    1362
#define IDC_CHECK_AUTO_CROTCH_SPECIAL   1363
#define IDC_SCROLL_WATER_MAX_SCREEN_RES 1364
#define IDC_STATIC_WATER_MAX_SCREEN_RES 1365
#define IDC_SCROLL_WATER_MAX_WORLD_RES  1366
#define IDC_STATIC_WATER_MAX_WORLD_RES  1367
#define IDC_CHECK_HEAD_FOLLOW_HAND      1368
#define IDC_CHECK_HW                    1369
#define IDC_QUALITY_TEXT                1370
#define IDC_EDIT_MAG_RESTORE            1371
#define IDC_EDIT_MAG_FRICTION           1372
#define IDC_STATIC_MIN_AMBIENT          1372
#define IDC_EDIT_MAG_MIN                1373
#define IDC_VOLUME_TEXT                 1373
#define IDC_EDIT_MAG_MAX                1374
#define IDC_DECAY_TEXT                  1374
#define IDC_EDIT_MAG_DRIVE              1375
#define IDC_DAMPING_TEXT                1375
#define IDC_CURR_X                      1376
#define IDC_CURR_Y                      1377
#define IDC_CURR_Z                      1378
#define IDC_TELE_X                      1379
#define MENU_WIREFRAME                  1999
#define MENU_WINDOW                     2000
#define MENU_DRIVER_FIRST               2500
#define MENU_PROFILE_STAT               3000
#define MENU_OPEN_LAST                  4000
#define MENU_HARDWARE                   8599
#define IDS_STR_HINTS                   18000
#define MENU_SHOWTOOLBAR                32772
#define MENU_ABOUT                      32780
#define MENU_TEXTURE                    32782
#define MENU_ADDOBJECT                  32783
#define MENU_DELETE                     32784
#define MENU_PROPERTIES                 32785
#define MENU_CAMERAPROPERTIES           32786
#define MENU_AMBIENT                    32787
#define MENU_DIRECTIONAL                32789
#define MENU_POINT                      32790
#define MENU_POINTDIRECTIONAL           32791
#define MENU_BACKGROUND                 32792
#define ID_EDIT_ADDSOUND_POINT          32795
#define ID_EDIT_ADDSOUND_AMBIENT        32796
#define ID_EDIT_ADDSOUND_MUSIC          32797
#define ID_EDIT_SOUNDPROPERTIES         32798
#define ID_EDIT_AUDIOPROPERTIES         32798
#define MENU_PREDICTMOVEMENT            32799
#define ID_EDIT_PLAYAUDIO               32800
#define ID_EDIT_STOPAUDIO               32801
#define MENU_LIGHTING                   32802
#define MENU_LIGHT_SHADE                32803
#define MENU_LIGHT                      32804
#define MENU_FOG                        32805
#define MENU_FOG_SHADE                  32806
#define MENU_COLOURED                   32807
#define MENU_BUMP                       32808
#define MENU_FILTER                     32809
#define MENU_FILTER_EDGES               32810
#define MENU_PERSPECTIVE                32811
#define MENU_SUBPIXEL                   32812
#define MENU_DITHER                     32813
#define MENU_ZBUFFER                    32814
#define MENU_RASTERCLIP                 32815
#define MENU_SCREENCLIP                 32816
#define MENU_SCREENCULL                 32817
#define MENU_TRANSPARENT                32818
#define MENU_SPECULAR                   32819
#define MENU_EDIT_FOG                   32820
#define MENU_STATS                      32821
#define MENU_BUMPMAP                    32823
#define MENU_PAUSE                      32824
#define MENU_PLAY                       32825
#define MENU_DEBUG                      32826
#define MENU_WATER                      32827
#define MENU_FPS_ESTIMATE               32828
#define MENU_PRESORT_NONE               32829
#define MENU_PRESORT_FTOB               32830
#define MENU_PRESORT_BTF                32831
#define ID_ACTION_SHOWFPS               32832
#define MENU_FPS                        32833
#define MENU_PLAYERPHYSICS              32835
#define MENU_PLAYERHEAD                 32836
#define ID_EDIT_GAMMA                   32837
#define MENU_EDIT_GAMMA                 32838
#define MENU_AVG_STATS                  32839
#define MENU_EDIT_PERSPECTIVE           32840
#define MENU_RENDER_CACHE               32842
#define MENU_RENDER_CACHE_BORDER        32843
#define MENU_RENDER_CACHE_TEST          32844
#define MENU_RENDERCACHE_SETTINGS       32845
#define MENU_CACHE_STATS                32846
#define MENU_SYSTEM_MEM                 32847
#define MENU_PLAYERINVULNERABLE         32848
#define MENU_ATTACH                     32849
#define MENU_CONSOLE                    32852
#define MENU_FASTMODE                   32853
#define MENU_AUDIO_ENVIRONMENT          32854
#define MENU_TERRAIN                    32855
#define MENU_DELAUNAYTEST               32856
#define MENU_CACHE_INTERSECT            32857
#define MENU_CONPHYSICS                 32858
#define MENU_CONTERRAIN                 32859
#define MENU_CONSHADOWS                 32860
#define MENU_CONAI                      32861
#define MENU_SHADOWS                    32862
#define MENU_SMACKSELECTED              32863
#define MENU_DEPTHSORT                  32864
#define MENU_STATS_DEPTHSORT            32865
#define MENU_REPLAYLOAD                 32866
#define MENU_REPLAYSAVE                 32867
#define MENU_TERRAIN_SETTINGS           32868
#define MENU_LOAD_TERRAIN               32869
#define MENU_ADD_SKELETON               32870
#define MENU_ADD_SKY                    32871
#define ID_VIEW_BOUNDINGSPHERES         32872
#define MENU_VIEW_BOUNDINGSPHERES       32873
#define MENU_TERRAINTEST                32874
#define MENU_HEIGHTMAP                  32876
#define MENU_CONTROLS_DEFAULTCONTROLS   32877
#define MENU_CONTROLS_STANDARDJOYSTICK  32878
#define ID_OPTIONS_CONTROLS_DEFINECONTROLS 32879
#define MENU_PHYSICS                    32880
#define MENU_AI                         32881
#define MENU_CAMERAPLAYER               32885
#define MENU_CAMERASELECTED             32886
#define MENU_CAMERAFREE                 32887
#define MENU_DEPTHSORT_SETTINGS         32888
#define MENU_MODE1                      32889
#define MENU_MODE2                      32890
#define MENU_MODE3                      32891
#define MENU_VIEW_PINHEAD               32892
#define MENU_VIEW_SPHERES               32893
#define MENU_VIEW_WIRE                  32894
#define MENU_VIEW_BONES                 32895
#define MENU_SOUNDMATERIALPROPERTIES    32896
#define MENU_SOUND                      32897
#define MENU_SAVE_MATERIALS             32898
#define MENU_VIEW_PARTITIONS            32899
#define MENU_RESET                      32900
#define MENU_CAMERA2M                   32901
#define MENU_DOUBLEV                    32902
#define MENU_HALFSCAN                   32903
#define MENU_DETAIL                     32904
#define MENU_TRAPEZOIDS                 32907
#define MENU_PROCESSOR                  32908
#define MENU_ARTSTATS                   32909
#define MENU_CONVEXCACHES               32910
#define MENU_TEXTURE_WIRE               32911
#define MENU_TERRAIN_WIRE               32912
#define MENU_MIPMAP                     32913
#define MENU_SET_MIPMAP                 32914
#define MENU_ALPHA_COLOUR               32915
#define MENU_ALPHA_SHADE                32916
#define MENU_ALPHA_TEXTURE              32917
#define MENU_ALPHA_SETTINGS             32918
#define MENU_VIEW_QUADS                 32919
#define MENU_REDRAW_TEXTURE             32920
#define MENU_REDRAW_TERRAIN             32920
#define MENU_SHADOW_TERRAIN             32922
#define MENU_SHADOW_TERRAIN_MOVING      32923
#define MENU_STAT_CLOCKS                32930
#define MENU_STAT_MSR0                  32931
#define MENU_STAT_MSR1                  32932
#define MENU_STAT_RING3                 32939
#define MENU_STAT_RING0                 32940
#define MENU_STAT_SETMSR0               32947
#define MENU_STAT_SETMSR1               32948
#define MENU_TEXTUREPACK                32949
#define MENU_DEMAGNET                   32951
#define MENU_STATIC_HANDLES             32952
#define MENU_PHYSICS_SLEEP              32953
#define MENU_PHYSICS_PUTTOSLEEP         32954
#define MENU_SET                        32955
#define MENU_OPEN_SCENE                 32956
#define MENU_SAVE_SCENE                 32957
#define MENU_SAVE_AS_SCENE              32958
#define MENU_MODE4                      32960
#define MENU_MODE_3                     32961
#define MENU_MODE_4                     32962
#define MENU_MEMLOG_STATS               32963
#define MENU_PRELOAD                    32964
#define MENU_VIEW_HAIRS                 32965
#define MENU_PARTITIONS                 32966
#define IDS_ERROR_DDRAW_NOTFOUND        32966
#define MENU_RESET_SELECTED             32967
#define IDS_ERROR_DDRAW_FATAL           32967
#define MENU_VIEW_CROSSHAIR_RADIUS      32968
#define MENU_VIEW_CROSSHAIR_VEGETATION  32969
#define MENU_MIPMAP_NORMAL              32970
#define MENU_MIPMAP_SMALLEST            32971
#define MENU_MIPMAP_NO_LARGEST          32972
#define MENU_OCCLUDE_OBJECTS            32973
#define MENU_OCCLUDE_POLYGONS           32974
#define MENU_OCCLUDE_SETTINGS           32975
#define MENU_SMALLMOVESTEPS             32977
#define MENU_ZONLYEDIT                  32978
#define MENU_GIVEMEALIGHTL              32979
#define MENU_NAMESELECT                 32980
#define ID_EDIT_TERRAIN_TERRAINSOUNDS   32981
#define MENU_OCCLUSION_CONSOLE          32982
#define MENU_OCCLUDE_OCCLUDE            32983
#define MENU_OCCLUDE_CAMERAVIEWTEST     32984
#define MENU_SKY_DISABLE                32985
#define MENU_SKY_REMOVE                 32986
#define MENU_SKY_TEXTURE                32987
#define MENU_SKY_FILL                   32988
#define MENU_SKY_SETTINGS               32989
#define MENU_GUN_SETTINGS               32990
#define MENU_SCHEDULER_SETTINGS         32991
#define MENU_SCHEDULER_USE              32992
#define MENU_MAGNET_BREAK               32993
#define MENU_MAGNET_NOBREAK             32994
#define MENU_VIEW_TRIGGERS              32995
#define MENU_TEXTSAVE                   32996
#define MENU_DUMP_FIXEDHEAP             32997
#define MENU_VM_SETTINGS                32998
#define MENU_STRETCH                    32999
#define MENU_VIEW_CROSSHAIR_TERRAINTEXTURES 33000
#define MENU_BUMP_PACK                  33001
#define MENU_EDIT_AI                    33003
#define MENU_EDIT_AI_EMOTIONS           33004
#define MENU_PACK_OPTIONS               33005
#define MENU_EXPORT_TERRAIN_TRI         33006
#define MENU_FORCEINTERSECTING          33007
#define MENU_GRAB                       33008
#define MENU_DRAWPHYSICS                33009
#define MENU_STATPHYSICS                33009
#define MENU_SETTLEPHYSICS              33010
#define MENU_CULLING                    33011
#define MENU_ROTATE_WORLDZ              33012
#define MENU_ACCELERATION               33016
#define MENU_WATER_INTERPOLATE          33017
#define MENU_ASSERTSAVE                 33021
#define MENU_HARDWARE_STATS             33022
#define MENU_FILTER_CACHES              33023
#define MENU_PLAYER_PROP                33024
#define MENU_SLOW                       33025
#define MENU_PHYSICS_STEP               33026
#define MENU_MATERIAL_PROP              33027
#define MENU_PHYSICS_PROP               33028
#define MENU_WATER_TEXTURED             33029
#define MENU_WATER_ALPHA                33030
#define MENU_WATER_SETTINGS             33032
#define MENU_RESET_START_TRIGGERS       33033
#define MENU_FREEZECACHES               33034
#define MENU_SOUND_MATERIAL             33035
#define MENU_CHANGE_SMAT                33036
#define MENU_RESTORE_DEFAULTS           33037
#define MENU_SETTINGS_RENDERQUALITY     33038
#define MENU_CAMERASELECTEDHEAD         33039
#define MENU_VIEW_BONES_BOXES           33040
#define MENU_VIEW_BONES_WAKE            33041
#define MENU_VIEW_BONES_MAGNETS         33042
#define MENU_VIEW_BONES_SKELETONS       33043
#define MENU_VIEW_BONES_WATER           33044
#define MENU_VIEW_BONES_RAYCAST         33045
#define MENU_VIEW_BONES_QUERY           33046
#define MENU_VIEW_BONES_ATTACH          33047
#define MENU_VIEW_BONES_PHYSICS         33048
#define MENU_DRAWAI                     33049
#define MENU_LOADANIM                   33051
#define MENU_GRABCONTINOUS              33052
#define MENU_IGNORE_MSG_RECIPIENTS      33053
#define IDM_TELEPORT                    33054
#define MENU_SETTINGS_GORE              33055
#define MENU_GORE                       33055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         33056
#define _APS_NEXT_CONTROL_VALUE         1380
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
