#pragma once

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GroffExp.rc
//
#define KEY_FLOAT                       0
#define CALINE                          1
#define KEY_POS                         1
#define KEY_ROT                         2
#define KEY_SCL                         3
#define KEY_COLOR                       4
#define IDS_JP2_NO_ENUMERATED_INODES    101
#define IDS_JP2_CLASSNAME               102
#define IDS_JP2_LONGDESC                103
#define IDS_JP2_SHORTDESC               104
#define IDS_JP2_AUTHOR                  105
#define IDS_JP2_COPYRIGHT               106
#define IDS_JP2_EXTENSION               107
#define IDS_JP2_EXPORTER                108
#define IDS_SCENEENUM_START             109
#define IDD_EXPORT_OPTIONS              109
#define IDS_SCENEENUM_END               110
#define IDS_SCENEENUM_INODE             111
#define IDS_CONV_TO_TRIMESH             112
#define IDS_YES                         113
#define IDS_NO                          114
#define IDS_MATERIAL_CONFIG             115
#define IDS_FACE_MAP_ENABLED            116
#define IDS_FACE_MAP_DISABLED           117
#define IDS_FACE_MODE_DOUBLE            118
#define IDS_FACE_MODE_SINGLE            119
#define IDS_SHININESS                   120
#define IDS_SHININESS_STRENGTH          121
#define IDS_SELF_ILLUMINATION           122
#define IDS_AMBIENT_MAP                 123
#define IDS_DIFFUSE_MAP                 124
#define IDS_SPECULAR_MAP                125
#define IDS_SHININESS_MAP               126
#define IDS_SHININESS_STR_MAP           127
#define IDS_SELF_ILLUM_MAP              128
#define IDS_OPACITY_MAP                 129
#define IDS_FILTER_MAP                  130
#define IDS_BUMP_MAP                    131
#define IDS_REFLECTION_MAP              132
#define IDS_REFRACTION_MAP              133
#define IDS_JP2_NLG_SHORTDESC           134
#define IDS_MATRIX_SEPARATOR            134
#define IDS_JP2_NLG_CLASSNAME           135
#define IDS_OBJECT_SEPARATOR            135
#define IDS_TMBeforeWSM                 136
#define IDS_TMAfterWSM                  137
#define IDS_ObjectTM                    138
#define IDS_ParentTM                    139
#define IDS_NodeTM                      140
#define IDS_RelativeTM                  141
#define IDS_SCALE                       142
#define IDS_ROTATION                    143
#define IDS_TRANSLATION                 144
#define IDS_NO_GROFF_GEN                145
#define IDS_GROFF_GEN                   146
#define IDS_ERR_CONST_EXP_HIER          147
#define IDS_FILENAME_EXPORT             148
#define IDS_UNKNOWN_CHUNK               149
#define IDS_EQ_SEPARATOR                150
#define IDS_INDENT                      151
#define IDS_NEWLINE                     152
#define IDS_STR_CRLF                    153
#define IDS_PT3_CRLF                    154
#define IDS_FV3_CRLF                    155
#define IDS_QUAT                        156
#define IDS_ANGLE_AXIS                  157
#define IDS_MAT_SEPARATOR               158
#define IDS_DECOMP_TITLE1               159
#define IDS_SCALE_ROTATION              160
#define IDS_SCALE_FACTOR                161
#define IDS_DETERMINANT_SIGN            162
#define IDS_DECOMP_TITLE2               163
#define IDS_DASH_SEPARATOR              164
#define IDS_ABORT_OP                    165
#define IDS_ROOT_OBJECT                 166
#define IDS_CHILD_OBJECT                167
#define IDS_LEAF_OBJECT                 168
#define IDS_OAL_SOURCE                  169
#define IDS_WORLD_COORDS                170
#define IDS_LOCAL_COORDS                171
#define IDS_OBJ_OFF_TITLE1              172
#define IDS_PIVOT_OFF                   173
#define IDS_PIVOT_ROT                   174
#define IDS_NONUNI_SCALE_FMT            175
#define IDS_PLACE_TITLE                 176
#define IDS_OBJ_SCALING                 177
#define IDS_OBJ_POS                     178
#define IDS_OBJ_ROT_QUAT                179
#define IDS_F3_EULER                    180
#define IDS_MTL_TITLE                   181
#define IDS_MULTI_MTL                   182
#define IDS_SINGLE_MTL                  183
#define IDS_ERR_NO_MTLS                 184
#define IDS_WORLD_SPACE_TITLE           185
#define IDS_WORLD_VERTEX_FMT            186
#define IDS_ERR_NO_GEOMETRY             187
#define IDS_VERTEX_TITLE                188
#define IDS_VERTEX_DEFS                 189
#define IDS_FACES_TITLE                 190
#define IDS_FACE_DEFS                   191
#define IDS_FACE_NORMAL_TITLE           192
#define IDS_FACE_NORMAL_DEFS            193
#define IDS_VERTEX_NORMAL_TITLE         194
#define IDS_VERTEX_NORMAL_DEFS          195
#define IDS_FACE_MTL_TITLE              196
#define IDS_FACE_MTL_DEFS               197
#define IDS_TVERT_TITLE                 198
#define IDS_TVERT_DEFS                  199
#define IDS_TFACE_TITLE                 200
#define IDS_TFACE_DEFS                  201
#define IDS_QUANTIZE_BM                 202
#define IDS_INFO_MSG                    203
#define IDS_WARNING_MSG                 204
#define IDS_ERROR_MSG                   205
#define IDS_QUESTION                    206
#define IDS_BITMAP_PATH                 207
#define IDS_LOGFILE_PATH                208
#define IDS_PB_CANT_LOAD_DIF_BMP        209
#define IDS_QB_TEX_BMP_NOT_TRUECOLOR    210
#define IDS_QB_CANT_ALLOC_PXL_BUFFER    211
#define IDS_PXL_LOOP_READ_ERR           212
#define IDS_BITMAP_FMT                  213
#define IDS_BMP_TITLE                   214
#define IDS_BMP_WIDTH_FMT               215
#define IDS_BMP_HEIGHT_FMT              216
#define IDS_BMP_FLAGS_FMT               217
#define IDS_BMP_MAX_RGB_LVL_FMT         218
#define IDS_PB_DIF_BMP_NOT_TRUECOLOR    219
#define IDS_PB_DIF_BMP_TRUECOLOR        220
#define IDS_PB_CANT_CREATE_DST_TXT_BMP  221
#define IDS_PB_CANT_ALLOC_PXL_BUFFER    222
#define IDS_PB_CANT_CFG_NEW_IMG_PAL     223
#define IDS_PB_CANT_WR_PPXL_TO_BMP      224
#define IDS_PB_CANT_LOAD_OP_BMP         225
#define IDS_PB_BMP_DIMS_INCOMPAT        226
#define IDS_PB_OP_BMP_NOT_PAL           227
#define IDS_PB_CANT_RD_OP_BMP_PAL       228
#define IDS_PB_CANT_FIND_XPAR_PXL       229
#define IDS_PB_CANT_RD_OP_BMP_SCANLINE  230
#define IDS_PB_CANT_RD_DIF_BMP_SCANLINE 231
#define IDS_PB_CANT_WR_SCANLINE_2_DIF_BMP 232
#define IDS_PB_PXL_PRCS_STATS           233
#define IDS_PB_CANT_LOAD_BU_BMP         234
#define IDS_PB_CANT_UPDATE_DST_BU_NAME  235
#define IDS_PB_BU_BMP_NOT_PAL           236
#define IDS_PB_CANT_RD_BU_BMP_SCANLINE  237
#define IDS_PB_CANT_WR_SCANLINE_2_BU_BMP 238
#define IDS_PB_CANT_WR_BU_BMP_2_DSK     239
#define IDS_PB_UNKNOWN_BMP_TYPE         240
#define IDS_POB_CANT_ALLOC_QUANT        241
#define IDS_POB_CANT_ALLOC_HIST         242
#define IDS_QUANTIZING                  243
#define IDS_POB_MISSING_QUANTIZED_BMP   244
#define IDS_POB_MISSING_BU_BMP          245
#define IDS_QB_CANT_LOAD_DIF_BMP        246
#define IDS_SM_MISSING_MTL              247
#define IDS_SINGLE_MTL_DEF              248
#define IDS_MTL_CLASS_ID                249
#define IDS_SM_MUST_USE_SM              250
#define IDS_SM_DIF_BMP_ID               251
#define IDS_SM_DIF_MTL_INVALID_BMP      252
#define IDS_SM_DIF_BMP_MISSING          253
#define IDS_PB_CANT_LOAD_DIF_BMP2       254
#define IDS_BMP_MISSING_NAME            255
#define IDS_DIF_BMP_NAME                256
#define IDS_SM_OP_BMP_ID                257
#define IDS_SM_OP_MTL_INVALID_BMP       258
#define IDS_OP_BMP_NAME                 259
#define IDS_BU_BMP_NAME                 260
#define IDS_SM_BU_BMP_ID                261
#define IDS_SM_BU_MTL_INVALID_BMP       262
#define IDS_BU_STRENGTH                 263
#define IDS_MULTI_MTL_DEF               264
#define IDS_MM_MUST_USE_MM              265
#define IDS_SUB_MTL_COUNT               266
#define IDS_SUB_MTL_NUM                 267
#define IDS_MM_DIF_BMP_MISSING          268
#define IDS_MM_DIF_MTL_INVALID_BMP      269
#define IDS_EXP_FILENAME                270
#define IDS_MM_DIF_BMP_ID               271
#define IDS_MM_OP_BMP_ID                272
#define IDS_MM_OP_MTL_INVALID_BMP       273
#define IDS_MM_BU_BMP_ID                274
#define IDS_MM_BU_MTL_INVALID_BMP       275
#define IDS_INVALID_EXP_OBJ_TYPE        276
#define IDS_NO_ENUMERATED_INODES        277
#define IDS_JP2_ABOUT_BOX               278
#define IDS_JP2_ABOUT_TITLE             279
#define IDS_GEN_LOGFILES                280
#define IDS_QUANTIZE_BMPS               281
#define IDS_QUANT_AND_GEN_LOGS          282
#define IDS_BBOX_TITLE                  283
#define IDS_BBOX_LOWER_COORD            284
#define IDS_BBOX_UPPER_COORD            285
#define IDS_BBOX_CENTER_COORD           286
#define IDS_OBJ_BBOX                    287
#define IDC_CHECK1                      1000
#define IDC_GEN_LOGFILES                1000
#define IDC_QUANTIZE_BMP                1001
#define IDC_GEN_GROFF                   1002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
