#pragma once

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CollisionEditor.rc
//
#define IDC_SAVE_LIST                   2
#define IDC_EM_TEST                     3
#define IDC_TEST_SAMPLE                 3
#define IDC_EM_TESTRAW                  4
#define IDC_EM_CENTER                   5
#define IDC_COLLIDE                     6
#define IDC_TEST_MATERIAL               7
#define IDC_STOP_COLLIDE                7
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COLLISIONEDITOR_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_ADDMATERIAL_DIALOG          129
#define IDD_EDITMATERIAL_DIALOG         130
#define IDD_TESTMATERIAL_DIALOG         131
#define IDD_SAMPLE_LIST                 134
#define IDD_SAMPLE_PROP                 134
#define IDC_SURFACE_LIST                1000
#define IDC_ADD                         1001
#define IDC_MSET_M2_LIST                1001
#define IDC_DELETE                      1002
#define IDC_REFWF_S1                    1002
#define IDC_OBJECT_LIST                 1002
#define IDC_EDIT                        1003
#define IDC_REFWF_S2                    1003
#define IDC_LOADFILE                    1004
#define IDC_MSET_LIST                   1004
#define IDC_TEST                        1005
#define IDC_REFWF_S3                    1005
#define IDC_TEST_EFFECT                 1005
#define IDC_WRITEFILE                   1006
#define IDC_REFWF_S4                    1006
#define IDC_PLAYCOL                     1007
#define IDC_LISTSAMPLE                  1007
#define IDC_STOP_EFFECT                 1007
#define IDC_PLAYOBJ                     1008
#define IDC_WRITEBINFILE                1008
#define IDC_PLAYSURF                    1009
#define IDC_BROWSE                      1009
#define IDC_DELFROM_M2                  1010
#define IDC_NEW_EFFECT                  1010
#define IDC_RENAME_EFFECT               1011
#define IDC_DELETE_EFFECT               1012
#define IDC_REFWF_BROWSE_S1             1013
#define IDC_RENAME                      1013
#define IDC_REFWF_BROWSE_S2             1014
#define IDC_SAMPLE_PROP                 1014
#define IDC_REFWF_BROWSE_S3             1015
#define IDC_COPY                        1015
#define IDC_REFWF_BROWSE_S4             1016
#define IDC_REFWF_TEST_S1               1017
#define IDC_VOLF_SLOPE_SPIN             1018
#define IDC_REFWF_TEST_S2               1018
#define IDC_VOLF_SLOPE                  1019
#define IDC_REFWF_TEST_S3               1019
#define IDC_VELCUTOFF_SPIN              1020
#define IDC_REFWF_TEST_S4               1020
#define IDC_VELCUTOFF                   1021
#define IDC_VOLF_MIN_SPIN               1022
#define IDC_VOLF_MIN                    1023
#define IDC_VOLF_MAX_SPIN               1024
#define IDC_VOLF_MAX                    1025
#define IDC_VELOCITY_SLIDER             1027
#define IDC_MATERIAL_LIST               1029
#define IDC_ADD_EDIT                    1030
#define IDC_MSET_M1_LIST                1031
#define IDC_ADDTO_M1                    1032
#define IDC_M2TOM1                      1032
#define IDC_ADDTO_M2                    1033
#define IDC_DELFROM_M1                  1034
#define IDC_M1TOM2                      1034
#define IDC_MATERIALNAME                1036
#define IDC_VELOCITY                    1037
#define IDC_PITCHF_SLOPE_SPIN           1038
#define IDC_PITCHF_SLOPE                1039
#define IDC_PITCHF_MIN_SPIN             1040
#define IDC_PITCHF_MIN                  1041
#define IDC_PITCHF_MAX_SPIN             1042
#define IDC_PITCHF_MAX                  1043
#define IDC_GRAPH_VOL                   1048
#define IDC_GRAPH_PIT                   1049
#define IDC_SLIDER1                     1050
#define IDC_SM_SLIDER1                  1050
#define IDC_VOL_SLOPE_TEXT              1051
#define IDC_SLIDER2                     1052
#define IDC_SM_SLIDER2                  1052
#define IDC_VOL_INTS_TEXT               1053
#define IDC_SLIDER3                     1054
#define IDC_SM_SLIDER3                  1054
#define IDC_VOL_MIN_TEXT                1055
#define IDC_SLIDER4                     1056
#define IDC_SM_SLIDER4                  1056
#define IDC_VOL_MAX_TEXT                1057
#define IDC_SLIDER5                     1058
#define IDC_SM_SLIDER5                  1058
#define IDC_PIT_SLOPE_TEXT              1059
#define IDC_SLIDER6                     1060
#define IDC_SM_SLIDER6                  1060
#define IDC_PIT_INTS_TEXT               1061
#define IDC_SLIDER7                     1062
#define IDC_SM_SLIDER7                  1062
#define IDC_PIT_MIN_TEXT                1063
#define IDC_SLIDER8                     1064
#define IDC_SM_SLIDER8                  1064
#define IDC_PIT_MAX_TEXT                1065
#define IDC_SLIDER9                     1067
#define IDC_SM_SLIDER9                  1067
#define IDC_RADIO1                      1068
#define IDC_SM_RADIO1                   1068
#define IDC_RADIO_ENG                   1068
#define IDC_RADIO2                      1069
#define IDC_SM_RADIO2                   1069
#define IDC_RADIO_FRN                   1069
#define IDC_RADIO3                      1070
#define IDC_SM_RADIO3                   1070
#define IDC_RADIO_GER                   1070
#define IDC_RADIO4                      1071
#define IDC_SM_RADIO4                   1071
#define IDC_RADIO_PRT                   1071
#define IDC_SLIDER10                    1072
#define IDC_SM_SLIDER10                 1072
#define IDC_RADIO_SPN                   1072
#define IDC_TEST_VEL_TEXT               1073
#define IDC_TEST_VELOCITY_TEXT          1073
#define IDC_RADIO_JAP                   1073
#define IDC_CUT_VEL_TEXT                1074
#define IDC_RADIO_CHN                   1074
#define IDC_CHECK1                      1075
#define IDC_DUAL_CHECK                  1075
#define IDC_CHECK_COLLISIONS            1075
#define IDC_SM_SLIDER11                 1076
#define IDC_SM_SLIDER12                 1077
#define IDC_SM_SLIDER14                 1078
#define IDC_SM_SLIDER13                 1079
#define IDC_WORLD_SCALE_TEXT            1080
#define IDC_ATTENUATE_TEXT              1081
#define IDC_GRAPH_WORLD                 1082
#define IDC_WORLD_POS_TEXT              1083
#define IDC_TRANSFER                    1084
#define IDC_LIST1                       1085
#define IDC_COLLISION_ENABLE            1085
#define IDC_SLIDE_ENABLE                1086
#define IDC_EFFECT_FILE_EDIT            1087
#define IDC_SM_SLIDER15                 1087
#define IDC_EFFECT_ID_EDIT              1088
#define IDC_MIN_VEL_TEXT                1088
#define IDC_EFFECT_LIST                 1089
#define IDC_STATIC2                     1091
#define IDC_STATIC1                     1092
#define IDC_COMBO1                      1093
#define IDC_COMBO2                      1094
#define IDC_TEXT_NEW_MAT                1094
#define IDC_TEXT_CUR_MAT                1095
#define IDC_COMBO3                      1095
#define IDC_DELAY_TIME                  1096
#define IDC_ATTEN_TEXT                  1097
#define IDC_VOL_TEXT                    1098

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
