//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by trespass.rc
//
#define IDS_TITLE                       1
#define IDS_ERROR_TITLE                 2
#define IDS_PROCESSORDETECT             3
#define IDS_ERROR_PROCESSORDETECT       4
#define IDS_NEWSAVE                     5
#define IDS_OVERWRITE_SAVEGAME          6
#define IDS_DELETE_SAVEGAME             7
#define IDS_EXIT_TRESPASSER             8
#define IDS_EXIT_GAME                   9
#define IDS_SAVEGAMEPREFIX              10
#define IDS_SAFEMODE                    11
#define IDS_RESTARTLEVEL                12
#define IDS_AUDIO_ERROR                 13
#define IDS_DISPLAY_ERROR               14
#define IDS_NOHARDWARE_ERROR            15
#define IDS_ERR_AUDIO_NOT_CERTIFIED     16
#define IDS_ERR_VIDEO_NOT_CERTIFIED     17
#define IDS_ERR_VIDEO_NO_HARDWARE       18
#define IDS_ERROR_DDRAW_NOTFOUND        19
#define IDS_ERROR_DDRAW_FATAL           20
#define IDS_NOT_INSTALLED               21
#define IDS_DATA_DRIVE_NOT_FOUND        22
#define IDS_ERROR_FATAL                 23
#define IDS_STR_KEY_MAP_UNKNOWN         24
#define IDS_RENDER_QUALITY_CHANGING     25
#define IDS_GORE_0                      26
#define IDS_GORE_1                      27
#define IDS_GORE_2                      28
#define IDS_ERROR_DISKSPACE_SAVE        29
#define IDS_ERROR_LOAD_UNKNOWN          30
#define IDS_ERROR_LOAD_INALID_SCENE     31
#define IDS_ERROR_NOT_ENOUGH_HD         32
#define IDS_ERROR_DISKSPACE             33
#define IDS_SOFTWARE_DRIVER             34
#define IDS_DISPLAY                     35
#define IDS_SOFTWARE                    36
#define IDS_LOADING_LEVEL               37
#define IDS_ERR_NEED_P6                 38
#define IDS_ERR_NEED_3DNOW              39
#define IDS_ERR_PDETECT_FAILED          40
#define IDS_ERR_NO_ACCELERATORS         41
#define IDS_ERR_DISPLAY_README          42
#define IDS_ERR_INVALID_DISPLAY_CONFIGURATION 43
#define IDI_APP                         101
#define IDTIMER_MAINRANDOM              101
#define IDB_DEF_PAL                     102
#define IDTIMER_MAININIT                102
#define IDD_RENDERING                   103
#define IDD_NEWGAME                     104
#define IDD_MAIN                        105
#define IDD_OPTIONS                     106
#define IDD_GAMEOPTIONS                 107
#define IDD_CONTROLS                    108
#define IDD_DIFFICULTY                  109
#define IDD_SOUND                       110
#define IDD_LOADGAME                    111
#define IDD_SAVEGAME                    112
#define IDD_HELP                        113
#define IDD_RENDERING_BASE              114
#define IDD_RENDERING_FOG               115
#define IDD_RENDERING_TERRAIN           116
#define IDB_CHECKBOX                    117
#define IDD_INITIALIZATION              120
#define IDD_DXERROR                     121
#define IDC_MODES                       1000
#define IDC_COMBO_VIDEOGUID             1000
#define IDC_ADAPTERS                    1001
#define IDC_CHECK_USED3D                1002
#define IDC_LIST                        1003
#define IDC_CHECK_FULLSCREEN            1003
#define IDC_COMBO_RESOLUTION            1004
#define IDC_STATIC_ADAPTERS             1005
#define IDC_CHECK_SYSTEMMEM             1005
#define IDC_COMBO_TEXTURESIZE           1005
#define IDC_STATIC_SIZES                1006
#define IDC_COMBO_D3D                   1006
#define IDC_STATIC_BOX                  1007
#define IDC_D3D                         1008
#define IDC_LIST_CARD                   1008
#define IDC_HARDWARE_ACCEL              1009
#define IDC_STATIC_D3D                  1010
#define IDC_SYSTEMMEM                   1011
#define IDC_NEWGAME                     1011
#define IDC_STATIC_OPTIONS              1012
#define IDC_CREDITS                     1012
#define IDC_OPTIONS                     1013
#define IDC_LOADGAME                    1014
#define IDC_QUIT                        1015
#define IDC_DIFFICULTY                  1015
#define IDC_STATIC_PID                  1016
#define IDC_CONTROLS                    1017
#define IDC_RENDERING                   1018
#define IDC_SOUND                       1019
#define IDC_SAVEGAME                    1021
#define IDC_SLIDER1                     1021
#define IDC_SLIDER2                     1022
#define IDC_LIST1                       1022
#define IDC_LISTSAVE                    1022
#define IDC_SLIDER3                     1023
#define IDC_HELPBOX                     1023
#define IDC_QUITGAME                    1024
#define IDC_TAB_VIDEO                   1025
#define IDC_AUDIOLEVEL                  1026
#define IDC_NAME                        1027
#define IDC_FILES                       1028
#define IDC_LEVEL_PICTURE               1029
#define IDC_EDIT1                       1030
#define IDC_EDIT_SAVE                   1032
#define IDC_LISTSCROLLBAR_V             1034
#define IDC_STATIC_VIDEODRIVER          1035
#define IDC_MESSAGE                     1036
#define IDC_NODISPLAY                   1037
#define IDC_CHECK_HARDWAREWATER         1038
#define IDC_CHECK_TRIPLEBUFFER          1039
#define IDC_CHECK_DITHER                1040
#define IDC_CHECK_PAGEMANAGED           1041
#define IDC_EFFECTS                     1161
#define IDC_VOICEOVER                   1167
#define IDC_AMBIENT                     1168
#define IDC_MUSIC                       1169
#define IDS_STR_CONTROLS_TEXT           10000
#define IDS_STR_KEY_MAP                 16000
#define IDS_STR_HINTS                   18000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
