#pragma once

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Errors.rc
//
#define ERROR_UNDEFINED						1000
#define ERROR_TIMER							1001
#define ERROR_CREATEWINDOW					1002
#define ERROR_NODEVICECONTEXT				1003
#define ERROR_ASSERTFAIL					1004
#define ERROR_NOMEMORY						1005
#define ERROR_DIRECTDRAW					1006
#define ERROR_D3D							1007
#define ERROR_FASTHEAP_OUTOFMEMORY			1008
#define ERROR_FASTHEAP_UNABLETOCREATE		1009
#define ERROR_INVALID_GAMMA					1010
#define ERROR_UNABLETOLOAD_MESH				1011
#define ERROR_UNABLETOLOAD_TEXTURE			1012
#define ERROR_UNABLETO_OPENGROFF			1013
#define ERROR_UNABLETO_READGROFFINFO		1014

//
// DirectDraw Error Codes.
//
#define ERROR_DD_BASE						5000
#define ERROR_DD_INVALIDPARAMS				5003
#define ERROR_DD_ALREADYINITIALIZED			5005
#define ERROR_DD_CANNOTATTACHSURFACE		5010
#define ERROR_DD_OUTOFMEMORY				5014
#define ERROR_DD_CANNOTDETACHSURFACE		5020
#define ERROR_DD_CURRENTLYNOTAVAIL			5040
#define ERROR_DD_EXCEPTION					5055
#define ERROR_DD_HEIGHTALIGN				5090
#define ERROR_DD_INCOMPATIBLEPRIMARY		5095
#define ERROR_DD_INVALIDCAPS				5100
#define ERROR_DD_INVALIDCLIPLIST			5110
#define ERROR_DD_INVALIDMODE				5120
#define ERROR_DD_INVALIDOBJECT				5130
#define ERROR_DD_INVALIDPIXELFORMAT			5145
#define ERROR_DD_INVALIDRECT				5150
#define ERROR_DD_LOCKEDSURFACES				5160
#define ERROR_DD_NO3D						5170
#define ERROR_DD_NOALPHAHW					5180
#define ERROR_DD_NOCLIPLIST					5205
#define ERROR_DD_NOCOLORCONVHW				5210
#define ERROR_DD_NOCOOPERATIVELEVELSET		5212
#define ERROR_DD_NOCOLORKEY					5215
#define ERROR_DD_NOCOLORKEYHW				5220
#define ERROR_DD_NODIRECTDRAWSUPPORT		5222
#define ERROR_DD_NOEXCLUSIVEMODE			5225
#define ERROR_DD_NOFLIPHW					5230
#define ERROR_DD_NOGDI						5240
#define ERROR_DD_NOMIRRORHW					5250
#define ERROR_DD_NOTFOUND					5255
#define ERROR_DD_NOOVERLAYHW				5260
#define ERROR_DD_NORASTEROPHW				5280
#define ERROR_DD_NOROTATIONHW				5290
#define ERROR_DD_NOSTRETCHHW				5310
#define ERROR_DD_NOT4BITCOLOR				5316
#define ERROR_DD_NOT4BITCOLORINDEX			5317
#define ERROR_DD_NOT8BITCOLOR				5320
#define ERROR_DD_NOTEXTUREHW				5330
#define ERROR_DD_NOVSYNCHW					5335
#define ERROR_DD_NOZBUFFERHW				5340
#define ERROR_DD_NOZOVERLAYHW				5350
#define ERROR_DD_OUTOFCAPS					5360
#define ERROR_DD_OUTOFVIDEOMEMORY			5380
#define ERROR_DD_OVERLAYCANTCLIP			5382
#define ERROR_DD_OVERLAYCOLORKEYONLYONEACTIVE 5384
#define ERROR_DD_PALETTEBUSY				5387
#define ERROR_DD_COLORKEYNOTSET				5400
#define ERROR_DD_SURFACEALREADYATTACHED		5410
#define ERROR_DD_SURFACEALREADYDEPENDENT	5420
#define ERROR_DD_SURFACEBUSY				5430
#define ERROR_DD_CANTLOCKSURFACE			5435
#define ERROR_DD_SURFACEISOBSCURED			5440
#define ERROR_DD_SURFACELOST				5450
#define ERROR_DD_SURFACENOTATTACHED			5460
#define ERROR_DD_TOOBIGHEIGHT				5470
#define ERROR_DD_TOOBIGSIZE					5480
#define ERROR_DD_TOOBIGWIDTH				5490
#define ERROR_DD_NOTINITIALIZED				5496
#define ERROR_DD_UNSUPPORTEDFORMAT			5510
#define ERROR_DD_UNSUPPORTEDMASK			5520
#define ERROR_DD_VERTICALBLANKINPROGRESS	5537
#define ERROR_DD_WASSTILLDRAWING			5540
#define ERROR_DD_XALIGN						5560
#define ERROR_DD_INVALIDDIRECTDRAWGUID		5561
#define ERROR_DD_DIRECTDRAWALREADYCREATED	5562
#define ERROR_DD_NODIRECTDRAWHW				5563
#define ERROR_DD_PRIMARYSURFACEALREADYEXISTS 5564
#define ERROR_DD_NOEMULATION				5565
#define ERROR_DD_REGIONTOOSMALL				5566
#define ERROR_DD_CLIPPERISUSINGHWND			5567
#define ERROR_DD_NOCLIPPERATTACHED			5568
#define ERROR_DD_NOHWND						5569
#define ERROR_DD_HWNDSUBCLASSED				5570
#define ERROR_DD_HWNDALREADYSET				5571
#define ERROR_DD_NOPALETTEATTACHED			5572
#define ERROR_DD_NOPALETTEHW				5573
#define ERROR_DD_BLTFASTCANTCLIP			5574
#define ERROR_DD_NOBLTHW					5575
#define ERROR_DD_NODDROPSHW					5576
#define ERROR_DD_OVERLAYNOTVISIBLE			5577
#define ERROR_DD_NOOVERLAYDEST				5578
#define ERROR_DD_INVALIDPOSITION			5579
#define ERROR_DD_NOTAOVERLAYSURFACE			5580
#define ERROR_DD_EXCLUSIVEMODEALREADYSET	5581
#define ERROR_DD_NOTFLIPPABLE				5582
#define ERROR_DD_CANTDUPLICATE				5583
#define ERROR_DD_NOTLOCKED					5584
#define ERROR_DD_CANTCREATEDC				5585
#define ERROR_DD_NODC						5586
#define ERROR_DD_WRONGMODE					5587
#define ERROR_DD_IMPLICITLYCREATED			5588
#define ERROR_DD_NOTPALETTIZED				5589
#define ERROR_DD_UNSUPPORTEDMODE			5590
#define ERROR_DD_NOMIPMAPHW					5591
#define ERROR_DD_INVALIDSURFACETYPE			5592
#define ERROR_DD_DCALREADYCREATED			5620
#define ERROR_DD_CANTPAGELOCK				5640
#define ERROR_DD_CANTPAGEUNLOCK				5660
#define ERROR_DD_NOTPAGELOCKED				5680
#define ERROR_D3D_BASE						6000
#define ERROR_D3D_REFERENCECOUNT			6001
#define ERROR_D3D_INVALIDPARAMS				6003
#define ERROR_D3D_INVALIDOBJECT				6130

//
// D3D Error Codes.
//
#define ERROR_D3D_TEXTURE_BADSIZE			6738
#define ERROR_D3D_TEXTURE_CREATE_FAILED		6721
#define ERROR_D3D_TEXTURE_DESTROY_FAILED	6722
#define ERROR_D3D_TEXTURE_GETSURF_FAILED	6729
#define ERROR_D3D_TEXTURE_LOAD_FAILED		6725
#define ERROR_D3D_TEXTURE_LOCK_FAILED		6723
#define ERROR_D3D_TEXTURE_UNLOCK_FAILED		6724
#define ERROR_D3D_TEXTURE_LOCKED			6727
#define ERROR_D3D_TEXTURE_NO_SUPPORT		6720
#define ERROR_D3D_TEXTURE_NOT_LOCKED		6728
#define ERROR_D3D_TEXTURE_SWAP_FAILED		6726
#define ERROR_D3D_INITIALIZATION_FAILED		6799	

//
// Generic Error Codes.
//
#define ERROR_DD_UNSUPPORTED				21385
#define ERROR_DD_GENERIC					21389

//
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE			101
#define _APS_NEXT_COMMAND_VALUE				40001
#define _APS_NEXT_CONTROL_VALUE				1000
#define _APS_NEXT_SYMED_VALUE				101
#endif
#endif
